### PR TITLE
 Update chat input to support multiline wrapping and adding new lines with Shift + Enter

### LINKED ISSUE #16: chat box should wrap when composing a long message

### PR DESCRIPTION
**Pull request by Johnnycus**
closes #16

### CODE REVIEW

**Comment by Johnnycus** [comment]
telegram web uses the same contenteditable div btw lol

**Comment by fplord** [comment]
is this ready for merge?

**Comment by Johnnycus** [comment]
> is this ready for merge?

yeah i think its looks/works good

**Comment by fplord** [comment]
> > is this ready for merge?
> 
> yeah i think its looks/works good

shift enter does not work on mobile, tested on FF Android.

**Pull request merged**
