### PR TITLE
Rewrite game in raw JS/Canvas

### PR DESCRIPTION
**Pull request by fplord**

### CODE REVIEW

**Comment by fplord** [comment]
Stuff that still needs to be done

- [ ] Camera
- [ ] Touch-to-move ( + deterministic update loop every 40ms)
- [ ] Collision
- [ ] Receive message from client + display message bubbles

**Comment by fplord** [comment]
- [x] touch-to-move ✅

**Comment by fplord** [comment]
- [x] camera (https://github.com/robashton/camera)

**Comment by fplord** [comment]
- [x] receive message from client + shitty bubbles (need word wrap)

**Comment by fplord** [comment]
merged master to this

**Comment by fplord** [comment]
better bubbles (but still shitty)

image

image

**Review by billythedummy — APPROVED** [review]
delete game.html first?

**Pull request merged**
