### PR TITLE
Show image preview if it's available in msg you're replying to and add deselect btn

### PR DESCRIPTION
**Pull request by Johnnycus**

### CODE REVIEW

**Review by billythedummy — COMMENTED** [review]
image

erm i think the styles are a bit off?

**Comment by Johnnycus** [comment]
> image
> 
> erm i think the styles are a bit off?

what the hell the positioning was wrong so i had to adjust in this pr. though its fine now on master. just merged master and got rid of positioning adjusting from in this branch

**Comment by Johnnycus** [comment]
added deseelct reply button

**Review by billythedummy — APPROVED** [review]
very nice, this is starting to look like a legit chat app

**Pull request merged**
